name: build-and-deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Artifacts and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - run: flutter pub get
      
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
      
      # Run widget tests for our flutter project.
      - run: flutter test
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Build apk.
      - run: flutter build apk
      
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
      
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

        #11 Check if Tag Exists
      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

        #12 Modify Tag if it Exists
      - name: Modify Tag
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV
        
        #13 Create Release
      - name: Create Release
        id: upload_apk
        uses: svenstaro/upload-release-action@v2
        with:
          file: "build/app/outputs/apk/release/app-release.apk"
          tag: v${{ env.VERSION }}

      - name: Post to a Slack channel
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_COLOR: ${{ job.status == 'success' && '#36a64f' || '#FF0000' }}  # Ternary operator to set color based on job status
          JOB_STATUS: ${{ job.status }}
        with:
          channel-id: 'C07GVCRDT0E'    
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*GitHub Action Build Result:*\n*Status:* `${{ job.status }}`\n*Details:* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|Visit here>"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n <${{github.server_url}}/${{ github.repository }}|${{ github.repository }}>\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n `${{ github.ref }}`\n"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*APK Download Link:*\n<${{ steps.upload_apk.outputs.browser_download_url }}|Download APK>"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Triggered by: ${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Commit SHA: ${{ github.sha }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "Build ID: ${{ github.run_id }}\n"
                    }
                  ]
                }
              ]
            }
